development:
  #host: localhost
  database: gma_monitoramento_development

test:
  #host: localhost
  database: gma_monitoramento_test

# set these environment variables on your prod server
production:
  #host: localhost
  database: gma_monitoramento_development
  #uri: <%= ENV['MONGOHQ_URL'] %>
  #max_retries_on_connection_failure: 20
  #persist_in_safe_mode: true
  #skip_version_check: true

  #host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
